// export const server = "http://localhost:8000"
// export const server = "https://ashvamedha-fjrh.onrender.com";
export const server = "https://ashvamedha-25.onrender.com";

export const collegeList = [
  { name: "aiims", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835608/AIIMS_Bhubaneswar_logo_ohxgii.png"},
  { name: "aiims-a", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835608/AIIMS_Bhubaneswar_logo_ohxgii.png"},
  { name: "aiims-b", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835608/AIIMS_Bhubaneswar_logo_ohxgii.png"},
  { name: "aiims-c", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835608/AIIMS_Bhubaneswar_logo_ohxgii.png"},
  { name: "iitbbs", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835713/Indian_Institute_of_Technology_Bhubaneswar_Logo_g87f6j.svg"},
  { name: "iitbbs-a", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835713/Indian_Institute_of_Technology_Bhubaneswar_Logo_g87f6j.svg"},
  { name: "iitbbs-b", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835713/Indian_Institute_of_Technology_Bhubaneswar_Logo_g87f6j.svg"},
  { name: "iitbbs-c", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835713/Indian_Institute_of_Technology_Bhubaneswar_Logo_g87f6j.svg"},
  { name: "faculty-iitbbs", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835713/Indian_Institute_of_Technology_Bhubaneswar_Logo_g87f6j.svg"},
  { name: "faculty-iitbbs-a", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835713/Indian_Institute_of_Technology_Bhubaneswar_Logo_g87f6j.svg"},
  { name: "faculty-iitbbs-b", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835713/Indian_Institute_of_Technology_Bhubaneswar_Logo_g87f6j.svg"},
  { name: "faculty-iitbbs-c", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835713/Indian_Institute_of_Technology_Bhubaneswar_Logo_g87f6j.svg"},
  { name: "alumni-iitbbs", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835713/Indian_Institute_of_Technology_Bhubaneswar_Logo_g87f6j.svg"},
  { name: "alumni-iitbbs-a", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835713/Indian_Institute_of_Technology_Bhubaneswar_Logo_g87f6j.svg"},
  { name: "alumni-iitbbs-b", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835713/Indian_Institute_of_Technology_Bhubaneswar_Logo_g87f6j.svg"},
  { name: "alumni-iitbbs-c", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835713/Indian_Institute_of_Technology_Bhubaneswar_Logo_g87f6j.svg"},
  { name: "kiit", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835292/kiit_mfcxr1.png" },
  { name: "kiit-a", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835292/kiit_mfcxr1.png" },
  { name: "kiit-b", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835292/kiit_mfcxr1.png" },
  { name: "kiit-c", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835292/kiit_mfcxr1.png" },
  { name :"bgu", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761836066/Logo_O8OFeL51Ic_gr0zje.webp"},
  { name :"bgu-a", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761836066/Logo_O8OFeL51Ic_gr0zje.webp"},
  { name :"bgu-b", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761836066/Logo_O8OFeL51Ic_gr0zje.webp"},
  { name :"bgu-c", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761836066/Logo_O8OFeL51Ic_gr0zje.webp"},
  { name: "cv-raman", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835290/C._V._Raman_Global_University_Logo_p9coxk.png" },
  { name: "cv-raman-a", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835290/C._V._Raman_Global_University_Logo_p9coxk.png" },
  { name: "cv-raman-b", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835290/C._V._Raman_Global_University_Logo_p9coxk.png" },
  { name: "cv-raman-c", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835290/C._V._Raman_Global_University_Logo_p9coxk.png" },
  { name: "mcnl", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835287/images_5_1.jpeg_ks0zzr.jpg" },
  { name: "mcnl-a", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835287/images_5_1.jpeg_ks0zzr.jpg" },
  { name: "mcnl-b", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835287/images_5_1.jpeg_ks0zzr.jpg" },
  { name: "mcnl-c", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835287/images_5_1.jpeg_ks0zzr.jpg" },
  { name: "niser", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835294/1200px-National_Institute_of_Science_Education_and_Research.svg_ls8cgg.png" },
  { name: "niser-a", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835294/1200px-National_Institute_of_Science_Education_and_Research.svg_ls8cgg.png" },
  { name: "niser-b", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835294/1200px-National_Institute_of_Science_Education_and_Research.svg_ls8cgg.png" },
  { name: "niser-c", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835294/1200px-National_Institute_of_Science_Education_and_Research.svg_ls8cgg.png" },
  { name: "outr", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835286/Odisha_University_of_Technology_and_Research_Logo_d0ejkb.png" },
  { name: "outr-a", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835286/Odisha_University_of_Technology_and_Research_Logo_d0ejkb.png" },
  { name: "outr-b", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835286/Odisha_University_of_Technology_and_Research_Logo_d0ejkb.png" },
  { name: "outr-c", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835286/Odisha_University_of_Technology_and_Research_Logo_d0ejkb.png" },
  { name: "silicon", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835277/df8be4de2fbe2b39f7da4866d9ca45e3_wqehjg.jpg" },
  { name: "silicon-a", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835277/df8be4de2fbe2b39f7da4866d9ca45e3_wqehjg.jpg" },
  { name: "silicon-b", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835277/df8be4de2fbe2b39f7da4866d9ca45e3_wqehjg.jpg" },
  { name: "silicon-c", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835277/df8be4de2fbe2b39f7da4866d9ca45e3_wqehjg.jpg" },
  { name: "niis", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835285/images.jpeg_nnwco7.jpg" },
  { name: "niis-a", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835285/images.jpeg_nnwco7.jpg" },
  { name: "niis-b", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835285/images.jpeg_nnwco7.jpg" },
  { name: "niis-c", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835285/images.jpeg_nnwco7.jpg" },
  { name: "iiser", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835288/IISER_lqsnhi.png" },
  { name: "iiser-a", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835288/IISER_lqsnhi.png" },
  { name: "iiser-b", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835288/IISER_lqsnhi.png" },
  { name: "iiser-c", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835288/IISER_lqsnhi.png" },
  { name: "ssu", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835286/Sri_Sri_University_Logo_hcnqt5.png" },
  { name: "ssu-a", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835286/Sri_Sri_University_Logo_hcnqt5.png" },
  { name: "ssu-b", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835286/Sri_Sri_University_Logo_hcnqt5.png" },
  { name: "ssu-c", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835286/Sri_Sri_University_Logo_hcnqt5.png" },
  { name: "iiit", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835287/IIIT_BBS.jpeg_to4y6r.jpg" },
  { name: "iiit-a", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835287/IIIT_BBS.jpeg_to4y6r.jpg" },
  { name: "iiit-b", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835287/IIIT_BBS.jpeg_to4y6r.jpg" },
  { name: "iiit-c", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835287/IIIT_BBS.jpeg_to4y6r.jpg" },
  { name: "centurion", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835289/centurion_university_eoaf2c.png" },
  { name: "centurion-a", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835289/centurion_university_eoaf2c.png" },
  { name: "centurion-b", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835289/centurion_university_eoaf2c.png" },
  { name: "centurion-c", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835289/centurion_university_eoaf2c.png" },
  { name: "prananath", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835290/android-chrome-512x512_tfyvwj.png" },
  { name: "prananath-a", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835290/android-chrome-512x512_tfyvwj.png" },
  { name: "prananath-b", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835290/android-chrome-512x512_tfyvwj.png" },
  { name: "prananath-c", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835290/android-chrome-512x512_tfyvwj.png" },
  { name: "trident", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835277/Trident_Acadamy.jpeg_arfy9q.jpg" },
  { name: "trident-a", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835277/Trident_Acadamy.jpeg_arfy9q.jpg" },
  { name: "trident-b", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835277/Trident_Acadamy.jpeg_arfy9q.jpg" },
  { name: "trident-c", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835277/Trident_Acadamy.jpeg_arfy9q.jpg" },
  { name:"ict", logo:"https://res.cloudinary.com/diu6ioiov/image/upload/v1761835287/institute_of_chemical_technology_nsdpim.png" },
  { name:"ict-a", logo:"https://res.cloudinary.com/diu6ioiov/image/upload/v1761835287/institute_of_chemical_technology_nsdpim.png" },
  { name:"ict-b", logo:"https://res.cloudinary.com/diu6ioiov/image/upload/v1761835287/institute_of_chemical_technology_nsdpim.png" },
  { name:"ict-c", logo:"https://res.cloudinary.com/diu6ioiov/image/upload/v1761835287/institute_of_chemical_technology_nsdpim.png" },
  { name: "iiest", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761836638/Indian_Institute_of_Engineering_Science_and_Technology__Shibpur_Logo_olhanh.png"},
  { name: "iiest-a", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761836638/Indian_Institute_of_Engineering_Science_and_Technology__Shibpur_Logo_olhanh.png"},
  { name: "iiest-b", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761836638/Indian_Institute_of_Engineering_Science_and_Technology__Shibpur_Logo_olhanh.png"},
  { name: "iiest-c", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761836638/Indian_Institute_of_Engineering_Science_and_Technology__Shibpur_Logo_olhanh.png"},
  { name: "gita", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761836982/unnamed_xdrliw.png"},
  { name: "gita-a", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761836982/unnamed_xdrliw.png"},
  { name: "gita-b", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761836982/unnamed_xdrliw.png"},
  { name: "gita-c", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761836982/unnamed_xdrliw.png"},
  { name: "soa", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761837223/SOA-PNG_ej7eka.webp"},
  { name: "soa-a", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761837223/SOA-PNG_ej7eka.webp"},
  { name: "soa-b", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761837223/SOA-PNG_ej7eka.webp"},
  { name: "soa-c", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761837223/SOA-PNG_ej7eka.webp"},
  { name: "xim", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761837183/images_kua6bm.png"},
  { name: "xim-a", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761837183/images_kua6bm.png"},
  { name: "xim-b", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761837183/images_kua6bm.png"},
  { name: "xim-c", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761837183/images_kua6bm.png"},
  { name: "jatni-clg", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761837395/tp6puotwtxrcs1q6sekd_othx2i.png"},
  { name: "jatni-clg-a", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761837395/tp6puotwtxrcs1q6sekd_othx2i.png"},
  { name: "jatni-clg-b", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761837395/tp6puotwtxrcs1q6sekd_othx2i.png"},
  { name: "jatni-clg-c", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761837395/tp6puotwtxrcs1q6sekd_othx2i.png"},
  { name: "gift", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545445/IMG-20251108-WA0004_j3rron.jpg"},
  { name: "gift-a", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545445/IMG-20251108-WA0004_j3rron.jpg"},
  { name: "gift-b", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545445/IMG-20251108-WA0004_j3rron.jpg"},
  { name: "gift-c", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545445/IMG-20251108-WA0004_j3rron.jpg"},
  { name: "ouat", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545446/IMG-20251108-WA0007_k3ts5k.jpg"},
  { name: "ouat-a", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545446/IMG-20251108-WA0007_k3ts5k.jpg"},
  { name: "ouat-b", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545446/IMG-20251108-WA0007_k3ts5k.jpg"},
  { name: "ouat-c", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545446/IMG-20251108-WA0007_k3ts5k.jpg"},
  { name: "nit-rourkela", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545445/IMG-20251108-WA0005_e47tyk.jpg"},
  { name: "nit-rourkela-a", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545445/IMG-20251108-WA0005_e47tyk.jpg"},
  { name: "nit-rourkela-b", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545445/IMG-20251108-WA0005_e47tyk.jpg"},
  { name: "nit-rourkela-c", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545445/IMG-20251108-WA0005_e47tyk.jpg"},
  { name: "utkal", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545445/IMG-20251108-WA0002_b6eiqp.jpg"},
  { name: "utkal-a", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545445/IMG-20251108-WA0002_b6eiqp.jpg"},
  { name: "utkal-b", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545445/IMG-20251108-WA0002_b6eiqp.jpg"},
  { name: "utkal-c", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545445/IMG-20251108-WA0002_b6eiqp.jpg"},
  { name: "gec", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545452/IMG-20251108-WA0001_ty8hol.jpg"},
  { name: "gec-a", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545452/IMG-20251108-WA0001_ty8hol.jpg"},
  { name: "gec-b", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545452/IMG-20251108-WA0001_ty8hol.jpg"},
  { name: "gec-c", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545452/IMG-20251108-WA0001_ty8hol.jpg"},
  { name: "sbu", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545446/IMG-20251108-WA0006_yg1kau.jpg"},
  { name: "sbu-a", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545446/IMG-20251108-WA0006_yg1kau.jpg"},
  { name: "sbu-b", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545446/IMG-20251108-WA0006_yg1kau.jpg"},
  { name: "sbu-c", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545446/IMG-20251108-WA0006_yg1kau.jpg"},
  { name: "bjb", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545445/IMG-20251108-WA0003_iy2ftk.jpg"},
  { name: "bjb-a", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545445/IMG-20251108-WA0003_iy2ftk.jpg"},
  { name: "bjb-b", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545445/IMG-20251108-WA0003_iy2ftk.jpg"},
  { name: "bjb-c", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545445/IMG-20251108-WA0003_iy2ftk.jpg"},
  { name: "pmec", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545450/IMG-20251108-WA0008_ummll6.jpg"},
  { name: "pmec-a", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545450/IMG-20251108-WA0008_ummll6.jpg"},
  { name: "pmec-b", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545450/IMG-20251108-WA0008_ummll6.jpg"},
  { name: "pmec-c", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545450/IMG-20251108-WA0008_ummll6.jpg"},
];

export const collegeList2 = [
  { name: "aiims", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835608/AIIMS_Bhubaneswar_logo_ohxgii.png"},
  { name: "iitbbs", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835713/Indian_Institute_of_Technology_Bhubaneswar_Logo_g87f6j.svg"},
  { name: "faculty-iitbbs", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835713/Indian_Institute_of_Technology_Bhubaneswar_Logo_g87f6j.svg"},
  { name: "alumni-iitbbs", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835713/Indian_Institute_of_Technology_Bhubaneswar_Logo_g87f6j.svg"},
  { name: "kiit", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835292/kiit_mfcxr1.png" },
  { name :"bgu", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761836066/Logo_O8OFeL51Ic_gr0zje.webp"},
  { name: "cv-raman", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835290/C._V._Raman_Global_University_Logo_p9coxk.png" },
  { name: "mcnl", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835287/images_5_1.jpeg_ks0zzr.jpg" },
  { name: "niser", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835294/1200px-National_Institute_of_Science_Education_and_Research.svg_ls8cgg.png" },
  { name: "outr", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835286/Odisha_University_of_Technology_and_Research_Logo_d0ejkb.png" },
  { name: "silicon", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835277/df8be4de2fbe2b39f7da4866d9ca45e3_wqehjg.jpg" },
  { name: "niis", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835285/images.jpeg_nnwco7.jpg" },
  { name: "iiser", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835288/IISER_lqsnhi.png" },
  { name: "ssu", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835286/Sri_Sri_University_Logo_hcnqt5.png" },
  { name: "iiit", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835287/IIIT_BBS.jpeg_to4y6r.jpg" },
  { name: "centurion", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835289/centurion_university_eoaf2c.png" },
  { name: "prananath", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835290/android-chrome-512x512_tfyvwj.png" },
  { name: "trident", logo: "https://res.cloudinary.com/diu6ioiov/image/upload/v1761835277/Trident_Acadamy.jpeg_arfy9q.jpg" },
  { name: "ict", logo:"https://res.cloudinary.com/diu6ioiov/image/upload/v1761835287/institute_of_chemical_technology_nsdpim.png" },
  { name: "iiest", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761836638/Indian_Institute_of_Engineering_Science_and_Technology__Shibpur_Logo_olhanh.png"},
  { name: "gita", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761836982/unnamed_xdrliw.png"},
  { name: "xim", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761837183/images_kua6bm.png"},
  { name: "soa", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761837223/SOA-PNG_ej7eka.webp"},
  { name: "jatni-clg", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1761837395/tp6puotwtxrcs1q6sekd_othx2i.png"},
  { name: "gift", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545445/IMG-20251108-WA0004_j3rron.jpg"},
  { name: "ouat", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545446/IMG-20251108-WA0007_k3ts5k.jpg"},
  { name: "nit-rourkela", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545445/IMG-20251108-WA0005_e47tyk.jpg"},
  { name: "utkal", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545445/IMG-20251108-WA0002_b6eiqp.jpg"},
  { name: "gec", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545452/IMG-20251108-WA0001_ty8hol.jpg"},
  { name: "sbu", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545446/IMG-20251108-WA0006_yg1kau.jpg"},
  { name: "bjb", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545445/IMG-20251108-WA0003_iy2ftk.jpg"},
  { name: "pmec", logo : "https://res.cloudinary.com/diu6ioiov/image/upload/v1762545450/IMG-20251108-WA0008_ummll6.jpg"},
  { name: "NA", logo : ""},
];

export const sportList = [
  {
    name :"football",
    email : "football.admin@ashvamedha.in",
  },
  {
    name :"volleyball",
    email : "volleyball.admin@ashvamedha.in",
  },
  {
    name :"basketball",
    email : "basketball.admin@ashvamedha.in",
  },
  {
    name :"chess",
    email : "chess.admin@ashvamedha.in",
  },
  {
    name :"badminton",
    email : "badminton.admin@ashvamedha.in",
  },
  {
    name :"tabletennis",
    email : "tabletennis.admin@ashvamedha.in",
  },
  {
    name :"lawntennis",
    email : "lawntennis.admin@ashvamedha.in",
  },
  {
    name :"gym",
    email : "gym.admin@ashvamedha.in",
  },
  {
    name :"bgmi",
    email : "bgmi.admin@ashvamedha.in",
  },
  {
    name :"khokho",
    email : "khokho.admin@ashvamedha.in",
  }
]

export const fixtures = {
  day1: {
    tabletennis: [
      {
        matchName: "match1",
        matchType: "League Match",
        category: "men",
        team1: "iitbbs-b",
        team2: "ict-a",
        time: "9:00 am",
        location: "SAC TT Court-1",
      },
      {
        matchName: "match2",
        matchType: "League Match",
        category: "men",
        team1: "utkal",
        team2: "ouat",
        time: "9:00 am",
        location: "SAC TT Court-2",
      },
      {
        matchName: "match3",
        matchType: "League Match",
        category: "men",
        team1: "ict-a",
        team2: "iitbbs-c",
        time: "10:00 am",
        location: "SAC TT Court-1",
      },
      {
        matchName: "match4",
        matchType: "League Match",
        category: "men",
        team1: "iitbbs-a",
        team2: "ouat",
        time: "10:00 am",
        location: "SAC TT Court-2",
      },
      {
        matchName: "match5",
        matchType: "League Match",
        category: "men",
        team1: "iitbbs-a",
        team2: "utkal",
        time: "11:00 am",
        location: "SAC TT Court-1",
      },
      {
        matchName: "match6",
        matchType: "League Match",
        category: "men",
        team1: "nit-rourkela",
        team2: "ict-a",
        time: "12:00 pm",
        location: "SAC TT Court-1",
      },
      {
        matchName: "match7",
        matchType: "League Match",
        category: "men",
        team1: "ouat",
        team2: "ict-b",
        time: "12:00 pm",
        location: "SAC TT Court-2",
      },
      {
        matchName: "match8",
        matchType: "League Match",
        category: "men",
        team1: "iitbbs-c",
        team2: "niser",
        time: "3:30 pm",
        location: "SAC TT Court-1",
      },
      {
        matchName: "match9",
        matchType: "League Match",
        category: "men",
        team1: "iitbbs-c",
        team2: "nit-rourkela",
        time: "4:30 pm",
        location: "SAC TT Court-1",
      },
      {
        matchName: "match10",
        matchType: "League Match",
        category: "men",
        team1: "ict-a",
        team2: "niser",
        time: "4:30 pm",
        location: "SAC TT Court-2",
      },
      {
        matchName: "match11",
        matchType: "League Match",
        category: "men",
        team1: "nit-rourkela",
        team2: "iitbbs-b",
        time: "5:30 pm",
        location: "SAC TT Court-1",
      },
      {
        matchName: "match12",
        matchType: "League Match",
        category: "men",
        team1: "utkal",
        team2: "ict-b",
        time: "5:30 pm",
        location: "SAC TT Court-2",
      },
      {
        matchName: "match13",
        matchType: "League Match",
        category: "men",
        team1: "nit-rourkela",
        team2: "niser",
        time: "6:30 pm",
        location: "SAC TT Court-1",
      },
      {
        matchName: "match14",
        matchType: "League Match",
        category: "men",
        team1: "iitbbs-b",
        team2: "iitbbs-c",
        time: "6:30 pm",
        location: "SAC TT Court-2",
      },
      {
        matchName: "match15",
        matchType: "League Match",
        category: "men",
        team1: "iitbbs-b",
        team2: "niser",
        time: "7:30 pm",
        location: "SAC TT Court-1",
      },
      {
        matchName: "match16",
        matchType: "League Match",
        category: "men",
        team1: "iitbbs-a",
        team2: "ict-b",
        time: "7:30 pm",
        location: "SAC TT Court-2",
      },
    ],
    chess: [
      {
        matchName: "match1",
        matchType: "League Match",
        team1: "iitbbs-a",
        team2: "ict",
        time: "3:30pm",
        location: "LHL",
      },
      {
        matchName: "match2",
        matchType: "League Match",
        team1: "gita",
        team2: "faculty-iitbbs",
        time: "3:30pm",
        location: "LHL",
      },
      {
        matchName: "match3",
        matchType: "League Match",
        team1: "outr",
        team2: "nit-rourkela",
        time: "3:30pm",
        location: "LHL",
      },
      {
        matchName: "match4",
        matchType: "League Match",
        team1: "ict",
        team2: "nit-rourkela",
        time: "4:30pm",
        location: "LHL",
      },
      {
        matchName: "match5",
        matchType: "League Match",
        team1: "faculty-iitbbs",
        team2: "outr",
        time: "4:30pm",
        location: "LHL",
      },
      {
        matchName: "match6",
        matchType: "League Match",
        team1: "iitbbs",
        team2: "gita",
        time: "4:30pm",
        location: "LHL",
      },
      {
        matchName: "match7",
        matchType: "League Match",
        team1: "outr",
        team2: "iitbbs",
        time: "5:30pm",
        location: "LHL",
      },
    ],
    lawntennis: [
      {
        matchName: "match1",
        matchType: "League Match",
        category: "men",
        team1: "iitbbs",
        team2: "niser",
        time: "8:00 am to 9:30 am",
        location: "SAC LT Court-1",
      },
      {
        matchName: "match2",
        matchType: "League Match",
        category: "men",
        team1: "iitbbs",
        team2: "iiser",
        time: "8:00 am to 9:30 am",
        location: "SAC LT Court-2",
      },
      {
        matchName: "match3",
        matchType: "League Match",
        category: "men",
        team1: "aiims",
        team2: "iiser",
        time: "3:00 pm to 4:30 pm",
        location: "SAC LT Court-1",
      },
      {
        matchName: "match4",
        matchType: "League Match",
        category: "men",
        team1: "iiser",
        team2: "aiims",
        time: "3:00 pm to 4:30 pm",
        location: "SAC LT Court-2",
      },
      {
        matchName: "match5",
        matchType: "League Match",
        category: "men",
        team1: "aiims",
        team2: "niser",
        time: "5:00 pm to 6:30 pm",
        location: "SAC LT Court-1",
      },
      {
        matchName: "match6",
        matchType: "League Match",
        category: "men",
        team1: "aiims",
        team2: "iitbbs",
        time: "5:00 pm to 6:30 pm",
        location: "SAC LT Court-2",
      },
      {
        matchName: "match7",
        matchType: "League Match",
        category: "men",
        team1: "aiims",
        team2: "iiser",
        time: "7:00 pm to 8:30 pm",
        location: "SAC LT Court-1",
      },
      {
        matchName: "match8",
        matchType: "League Match",
        category: "men",
        team1: "niser",
        team2: "aiims",
        time: "7:00 pm to 8:30 pm",
        location: "SAC LT Court-2",
      },
    ],
    volleyball: [
      {
        matchName: "match1",
        matchType: "League Match",
        category: "men",
        team1: "gift",
        team2: "bgu",
        time: "8:00 am",
        location: "volleyball court",
      },
      {
        matchName: "match2",
        matchType: "League Match",
        category: "men",
        team1: "cv-raman",
        team2: "outr",
        time: "9:00 am",
        location: "volleyball court",
      },
      {
        matchName: "match3",
        matchType: "League Match",
        category: "men",
        team1: "niser",
        team2: "bgu",
        time: ":10:00 am",
        location: "volleyball court",
      },
      {
        matchName: "match4",
        matchType: "League Match",
        category: "men",
        team1: "centurion",
        team2: "xim",
        time: "11:00 am",
        location: "volleyball court",
      },
      {
        matchName: "match5",
        matchType: "League Match",
        category: "men",
        team1: "centurion",
        team2: "silicon",
        time: "3:00 pm",
        location: "volleyball court",
      },
      {
        matchName: "match6",
        matchType: "League Match",
        category: "men",
        team1: "outr",
        team2: "trident",
        time: "4:00 pm",
        location: "volleyball court",
      },
      {
        matchName: "match7",
        matchType: "League Match",
        category: "men",
        team1: "niser",
        team2: "gift",
        time: "5:00 pm",
        location: "volleyball court",
      },
      {
        matchName: "match8",
        matchType: "League Match",
        category: "men",
        team1: "iitbbs",
        team2: "gita",
        time: "6:00 pm",
        location: "volleyball court",
      },
      {
        matchName: "match9",
        matchType: "League Match",
        category: "men",
        team1: "cv-raman",
        team2: "trident",
        time: "7:00 pm",
        location: "volleyball court",
      },
      {
        matchName: "match10",
        matchType: "League Match",
        category: "men",
        team1: "silicon",
        team2: "xim",
        time: "8:00pm",
        location: "volleyball court",
      },
    ],
    basketball: [
      {
        matchName: "match1",
        matchType: "League Match",
        category: "men",
        team1: "ssu",
        team2: "cv-raman",
        time: "8:00 am to 9:00 am",
        location: "SAC BB Court-1",
      },
      {
        matchName: "match2",
        matchType: "League Match",
        category: "men",
        team1: "gec",
        team2: "kiit",
        time: "8:00 am to 9:00 am",
        location: "SAC BB Court-2",
      },
      {
        matchName: "match3",
        matchType: "League Match",
        category: "men",
        team1: "gift",
        team2: "iiit",
        time: "9:00 am to 10:00 am",
        location: "SAC BB Court-1",
      },
      {
        matchName: "match4",
        matchType: "League Match",
        category: "women",
        team1: "iitbbs",
        team2: "niser",
        time: "9:00 am to 10:00 am",
        location: "SAC BB Court-2",
      },
      {
        matchName: "match5",
        matchType: "League Match",
        category: "men",
        team1: "iitbbs",
        team2: "iiser",
        time: "10:00 am to 11:00 am",
        location: "SAC BB Court-1",
      },
      {
        matchName: "match6",
        matchType: "League Match",
        category: "women",
        team1: "cv-raman",
        team2: "bjb",
        time: "10:00 am to 11:00 am",
        location: "SAC BB Court-2",
      },
      {
        matchName: "match7",
        matchType: "League Match",
        category: "women",
        team1: "iiser",
        team2: "niser",
        time: "11:00 am to 12:00 pm",
        location: "SAC BB Court-1",
      },
      {
        matchName: "match8",
        matchType: "League Match",
        category: "men",
        team1: "centurion",
        team2: "outr",
        time: "11:00 am to 12:00 pm",
        location: "SAC BB Court-2",
      },
      {
        matchName: "match9",
        matchType: "League Match",
        category: "men",
        team1: "bgu",
        team2: "iiser",
        time: "12:00 pm to 1:00 pm",
        location: "SAC BB Court-1",
      },
      {
        matchName: "match10",
        matchType: "League Match",
        category: "men",
        team1: "cv-raman",
        team2: "niser",
        time: "12:00 pm to 1:00 pm",
        location: "SAC BB Court-2",
      },
      {
        matchName: "match11",
        matchType: "League Match",
        category: "women",
        team1: "silicon",
        team2: "niser",
        time: "3:00 pm to 4:00 pm",
        location: "SAC BB Court-1",
      },
      {
        matchName: "match12",
        matchType: "League Match",
        category: "men",
        team1: "centurion",
        team2: "kiit",
        time: "3:00 pm to 4:00 pm",
        location: "SAC BB Court-2",
      },
      {
        matchName: "match13",
        matchType: "League Match",
        category: "women",
        team1: "bjb",
        team2: "xim",
        time: "4:00 pm to 5:00 pm",
        location: "SAC BB Court-1",
      },
      {
        matchName: "match14",
        matchType: "League Match",
        category: "men",
        team1: "iiit",
        team2: "alumni-iitbbs",
        time: "4:00 pm to 5:00 pm",
        location: "SAC BB Court-2",
      },
      {
        matchName: "match15",
        matchType: "League Match",
        category: "women",
        team1: "iitbbs",
        team2: "iiser",
        time: "5:00 pm to 6:00 pm",
        location: "SAC BB Court-1",
      },
      {
        matchName: "match16",
        matchType: "League Match",
        category: "men",
        team1: "centurion",
        team2: "gec",
        time: "5:00 pm to 6:00 pm",
        location: "SAC BB Court-2",
      },
      {
        matchName: "match17",
        matchType: "League Match",
        category: "men",
        team1: "trident",
        team2: "gift",
        time: "7:00 pm to 8:00 pm",
        location: "SAC BB Court-1",
      },
      {
        matchName: "match18",
        matchType: "League Match",
        category: "men",
        team1: "iitbbs",
        team2: "bgu",
        time: "7:00 pm to 8:00 pm",
        location: "SAC BB Court-2",
      },
      {
        matchName: "match19",
        matchType: "League Match",
        category: "men",
        team1: "ssu",
        team2: "niser",
        time: "8:00 pm to 9:00 pm",
        location: "SAC BB Court-1",
      },
      {
        matchName: "match20",
        matchType: "League Match",
        category: "men",
        team1: "cv-raman",
        team2: "xim",
        time: "8:00 pm to 9:00 pm",
        location: "SAC BB Court-2",
      },
      {
        matchName: "match21",
        matchType: "League Match",
        category: "women",
        team1: "ssu",
        team2: "xim",
        time: "9:00 pm to 10:00 pm",
        location: "SAC BB Court-1",
      },
      {
        matchName: "match22",
        matchType: "League Match",
        category: "men",
        team1: "bgu",
        team2: "silicon",
        time: "9:00 pm to 10:00 pm",
        location: "SAC BB Court-2",
      },
    ],
    Gym: [
      {
        matchName: "match1",
        matchType: "gym",
        category: "women",
        time: "9:00 AM",
        location: "SAC gym",
      },

      {
        matchName: "match2",
        matchType: "gym",
        category: "men",
        time: "3:00 PM",
        location: "SAC gym",
      },
    ],
    football: [
      {
        matchName: "match1",
        matchType: "League Match",
        category: "men",
        team1: "niser",
        team2: "bgu",
        time: "7:00 am to 8:00 am",
        location: "SAC FB Court",
      },
      {
        matchName: "match2",
        matchType: "League Match",
        category: "men",
        team1: "ouat",
        team2: "iiser",
        time: "8:00 am to 9:00 am",
        location: "SAC FB Court",
      },
      {
        matchName: "match3",
        matchType: "League Match",
        category: "men",
        team1: "sbu",
        team2: "gita",
        time: "9:00 am to 10:00 am",
        location: "SAC FB Court",
      },
      {
        matchName: "match4",
        matchType: "League Match",
        category: "men",
        team1: "centurion",
        team2: "ict",
        time: "10:00 am to 11:00 am",
        location: "SAC FB Court",
      },

      {
        matchName: "match5",
        matchType: "Quarter Final 1",
        category: "men",
        team1: "tbd",
        team2: "tbd",
        time: "2:00 pm to 3:00 pm",
        location: "SAC FB Court",
      },
      {
        matchName: "match6",
        matchType: "Quarter Final 2",
        category: "men",
        team1: "tbd",
        team2: "tbd",
        time: "3:00 pm to 4:00 pm",
        location: "SAC FB Court",
      },
      {
        matchName: "match7",
        matchType: "Quarter Final 3",
        category: "men",
        team1: "tbd",
        team2: "tbd",
        time: "4:00 pm to 5:00 pm",
        location: "SAC FB Court",
      },
      {
        matchName: "match8",
        matchType: "Quarter Final 4",
        category: "men",
        team1: "tbd",
        team2: "tbd",
        time: "5:00 pm to 6:00 pm",
        location: "SAC FB Court",
      },
    ],
    badminton: [
      {
        matchName: "match1",
        matchType: "League Match",
        category: "men",
        team1: "ict",
        team2: "gec",
        time: "9:00am",
        location: "Badminton Court",
      },
      {
        matchName: "match2",
        matchType: "League Match",
        category: "men",
        team1: "outr-a",
        team2: "iitbbs-c",
        time: "9:00am",
        location: "Badminton Court",
      },
      {
        matchName: "match3",
        matchType: "League Match",
        category: "men",
        team1: "xim",
        team2: "iitbbs-a",
        time: "9:00am",
        location: "Badminton Court",
      },
      {
        matchName: "match4",
        matchType: "League Match",
        category: "men",
        team1: "iitbbs-a",
        team2: "niser-a",
        time: "10:30am",
        location: "Badminton Court",
      },
      {
        matchName: "match5",
        matchType: "League Match",
        category: "men",
        team1: "iitbbs-b",
        team2: "iiit-b",
        time: "10:30am",
        location: "Badminton Court",
      },
      {
        matchName: "match6",
        matchType: "League Match",
        category: "men",
        team1: "utkal",
        team2: "ict",
        time: "12:00am",
        location: "Badminton Court",
      },
      {
        matchName: "match7",
        matchType: "League Match",
        category: "men",
        team1: "niser-b",
        team2: "outr-b",
        time: "12:00am",
        location: "Badminton Court",
      },
      {
        matchName: "match8",
        matchType: "League Match",
        category: "men",
        team1: "cv-raman",
        team2: "bgu",
        time: "12:00am",
        location: "Badminton Court",
      },
      {
        matchName: "match9",
        matchType: "League Match",
        category: "men",
        team1: "kiit",
        team2: "aiims",
        time: "3:00pm",
        location: "Badminton Court",
      },
      {
        matchName: "match10",
        matchType: "Quater FInal 1",
        category: "men",
        team1: "tbd",
        team2: "tbd",
        time: "5:00pm",
        location: "Badminton Court",
      },
      {
        matchName: "match11",
        matchType: "Quater FInal 2",
        category: "men",
        team1: "tbd",
        team2: "tbd",
        time: "6:30pm",
        location: "Badminton Court",
      },
      {
        matchName: "match12",
        matchType: "Quater FInal 3",
        category: "men",
        team1: "tbd",
        team2: "tbd",
        time: "6:30pm",
        location: "Badminton Court",
      },
      {
        matchName: "match13",
        matchType: "Quater FInal 4",
        category: "men",
        team1: "tbd",
        team2: "tbd",
        time: "6:30pm",
        location: "Badminton Court",
      },
    ],
    khokho: [
      {
        matchName: "match1",
        matchType: "League Match",
        category: "men",
        team1: "centurion",
        team2: "iiser",
        time: "9:00 am to 10:00 am",
        location: "SAC BB Court-1",
      },
      {
        matchName: "match2",
        matchType: "League Match",
        category: "men",
        team1: "gec",
        team2: "iitbbs-b",
        time: "10:00 am to 11:00 am",
        location: "SAC BB Court-1",
      },
      {
        matchName: "match3",
        matchType: "League Match",
        category: "men",
        team1: "tbd",
        team2: "iiser",
        time: "11:00 am to 12:00 am",
        location: "SAC BB Court-1",
      },
      {
        matchName: "match4",
        matchType: "League Match",
        category: "men",
        team1: "gift",
        team2: "xim",
        time: "3:20 am to 4:20 am",
        location: "SAC BB Court-1",
      },
      {
        matchName: "match1",
        matchType: "League Match",
        category: "men",
        team1: "niser",
        team2: "iitbbs-a",
        time: "4:20 am to 5:20 am",
        location: "SAC BB Court-1",
      },
    ],
  },

  day2: {
    khokho: [
      {
        matchName: "match5",
        matchType: "knockouts",
        category: "men",
        team1: "centurion",
        team2: "outr",
        time: "8:10 am to 10:00 am",
        location: "khokho ground",
      },
      {
        matchName: "match6",
        matchType: "semi-final",
        category: "men",
        team1: "gift",
        team2: "iitbbs-a",
        time: "9:00 am to 10:00 am",
        location: "khokho ground",
      },
      {
        matchName: "match7",
        matchType: "semi-final",
        category: "men",
        team1: "iitbbs-b",
        team2: "tbd",
        time: "10:00 am to 11:00 am",
        location: "khokho ground",
      },
      {
        matchName: "match8",
        matchType: "Final",
        category: "men",
        team1: "tbd",
        team2: "tbd",
        time: "4:00 pm to 5:00 pm",
        location: "khokho ground",
      },
    ],
    football: [
      {
        matchName: "match9",
        matchType: "semi-final",
        category: "men",
        team1: "cv-raman",
        team2: "iiser",
        time: "8:00 am to 9:00 am",
        location: "sac fb court",
      },
      {
        matchName: "match10",
        matchType: "semi final",
        category: "men",
        team1: "sbu",
        team2: "iitbbs-a",
        time: "9:00 am to 10:00 am",
        location: "sac fb court",
      },
      {
        matchName: "match11",
        matchType: "final",
        category: "men",
        team1: "tbd",
        team2: "tbd",
        time: "3:00 pm to 4:00 pm",
        location: "sac fb court",
      },
    ],
    basketball: [
      {
        matchName: "match23",
        matchType: "league match",
        category: "men",
        team1: "ssu",
        team2: "xim",
        time: "8:00 am to 9:00 am",
        location: "sac bb court-1",
      },
      {
        matchName: "match24",
        matchType: "league match",
        category: "men",
        team1: "alumni-iitbbs",
        team2: "trident",
        time: "8:00 am to 9:00 am",
        location: "sac bb court-2",
      },
      {
        matchName: "match25",
        matchType: "league match",
        category: "women",
        team1: "silicon",
        team2: "iiser",
        time: "9:00 am to 10:00 am",
        location: "sac bb court-1",
      },
      {
        matchName: "match26",
        matchType: "League Match",
        category: "men",
        team1: "gec",
        team2: "outr",
        time: "9:00 am to 10:00 am",
        location: "sac bb court-2",
      },
      {
        matchName: "match27",
        matchType: "League Match",
        category: "men",
        team1: "iitbbs",
        team2: "silicon",
        time: "10:00 am to 11:00 am",
        location: "sac bb court-1",
      },
      {
        matchName: "match28",
        matchType: "League Match",
        category: "women",
        team1: "ssu",
        team2: "bjb",
        time: "10:00 am to 11:00 am",
        location: "sac bb court-2",
      },
      {
        matchName: "match29",
        matchType: "league match",
        category: "men",
        team1: "niser",
        team2: "xim",
        time: "11:00 am to 12:00 pm",
        location: "sac bb court-1",
      },
      {
        matchName: "match30",
        matchType: "league match",
        category: "men",
        team1: "alumni-iitbbs",
        team2: "gift",
        time: "11:00 am to 12:00 pm",
        location: "sac bb court-2",
      },
      {
        matchName: "match31",
        matchType: "league match",
        category: "men",
        team1: "iiser",
        team2: "silicon",
        time: "12:00 pm to 1:00 pm",
        location: "sac bb court-1",
      },
      {
        matchName: "match32",
        matchType: "league match",
        category: "women",
        team1: "cv-raman",
        team2: "ssu",
        time: "12:00 pm to 1:00 pm",
        location: "sac bb court-2",
      },
      {
        matchName: "match33",
        matchType: "league match",
        category: "men",
        team1: "outr",
        team2: "kiit",
        time: "3:00 pm to 4:00 pm",
        location: "sac bb court-1",
      },
      {
        matchName: "match34",
        matchType: "league match",
        category: "women",
        team1: "cv-raman",
        team2: "xim",
        time: "3:00 pm to 4:00 pm",
        location: "sac bb court-2",
      },
      {
        matchName: "match35",
        matchType: "league match",
        category: "women",
        team1: "iitbbs",
        team2: "silicon",
        time: "4:00 pm to 5:00 pm",
        location: "sac bb court-1",
      },
      {
        matchName: "match36",
        matchType: "league match",
        category: "men",
        team1: "trident",
        team2: "iiit",
        time: "4:00 pm to 5:00 pm",
        location: "sac bb court-2",
      },
      {
        matchName: "match37",
        matchType: "semi-final",
        category: "men",
        team1: "tbd",
        team2: "tbd",
        time: "5:00 pm to 6:00 pm",
        location: "sac bb court-1",
      },
      {
        matchName: "match38",
        matchType: "semi-final",
        category: "men",
        team1: "tbd",
        team2: "tbd",
        time: "5:00 pm to 6:00 pm",
        location: "sac bb court-2",
      },
      {
        matchName: "match39",
        matchType: "final",
        category: "women",
        team1: "tbd",
        team2: "tbd",
        time: "6:00 pm to 7:00 pm",
        location: "sac bb court-2",
      },
      {
        matchName: "match40",
        matchType: "final",
        category: "men",
        team1: "tbd",
        team2: "tbd",
        time: "7:00 pm to 8:00 pm",
        location: "sac bb court-2",
      },
    ],
    chess: [
      {
        matchName: "match8",
        matchType: "round 3",
        category: "men",
        team1: "gita",
        team2: "ict",
        time: "2:00pm",
        location: "LHL",
      },
      {
        matchName: "match9",
        matchType: "round 3",
        category: "men",
        team1: "nit-rourkela",
        team2: "faculty-iitbbs",
        time: "2:00pm",
        location: "LHL",
      },
      {
        matchName: "match10",
        matchType: "round 4",
        category: "men",
        team1: "ict",
        team2: "faculty-iitbbs",
        time: "3:00pm",
        location: "LHL",
      },
      {
        matchName: "match11",
        matchType: "round 4",
        category: "men",
        team1: "iitbbs",
        team2: "nit-rourkela",
        time: "3:00pm",
        location: "LHL",
      },
      {
        matchName: "match12",
        matchType: "round 4",
        category: "men",
        team1: "gita",
        team2: "outr",
        time: "3:00pm",
        location: "LHL",
      },
      {
        matchName: "match13",
        matchType: "round 5",
        category: "men",
        team1: "outr",
        team2: "ict",
        time: "4:00pm",
        location: "LHL",
      },
      {
        matchName: "match14",
        matchType: "round 5",
        category: "men",
        team1: "nit-rourkela",
        team2: "gita",
        time: "4:00pm",
        location: "LHL",
      },
      {
        matchName: "match15",
        matchType: "round 5",
        category: "men",
        team1: "faculty-iitbbs",
        team2: "iitbbs",
        time: "4:00pm",
        location: "LHL",
      },
    ],
    lawntennis: [
      {
        matchName: "match9",
        matchType: "semi-final",
        category: "men",
        team1: "iitbbs-a",
        team2: "iiser-b",
        time: "4:00pm to 5:30pm",
        location: "sac tt court-1",
      },
      {
        matchName: "match10",
        matchType: "semi-final",
        category: "men",
        team1: "niser-b",
        team2: "aiims-b",
        time: "4:00pm to 5:30pm",
        location: "sac tt court-2",
      },
      {
        matchName: "match11",
        matchType: "final",
        category: "men",
        team1: "tbd",
        team2: "tbd",
        time: "6:00pm to 7:30pm",
        location: "sac tt court-1",
      },
    ],
    volleyball: [
      {
        matchName: "match11",
        matchType: "semi-final",
        category: "men",
        team1: "niser",
        team2: "gita",
        time: "3:00pm",
        location: "volleyball court",
      },
      {
        matchName: "match12",
        matchType: "semi-final",
        category: "men",
        team1: "centurion",
        team2: "cv-raman",
        time: "4:30pm",
        location: "volleyball court",
      },
      {
        matchName: "match13",
        matchType: "final",
        category: "women",
        team1: "iitbbs",
        team2: "niser",
        time: "4:30pm",
        location: "volleyball court",
      },
      {
        matchName: "match14",
        matchType: "final",
        category: "men",
        team1: "tbd",
        team2: "tbd",
        time: "6:00pm",
        location: "volleyball court",
      },
    ],
    tabletennis: [
      {
        matchName: "match17",
        matchType: "league match",
        category: "men",
        team1: "niser",
        team2: "nit-rourkela",
        time: "2:00pm",
        location: "SAC TT Court-1",
      },
      {
        matchName: "match18",
        matchType: "league match",
        category: "men",
        team1: "iitbbs-b",
        team2: "iitbbs-c",
        time: "2:00pm",
        location: "SAC TT Court-2",
      },
      {
        matchName: "match19",
        matchType: "semi-final",
        category: "men",
        team1: "tbd",
        team2: "tbd",
        time: "4:00PM",
        location: "SAC TT Court-1",
      },
      {
        matchName: "match20",
        matchType: "semi-final",
        category: "men",
        team1: "tbd",
        team2: "tbd",
        time: "4:00PM",
        location: "SAC TT Court-2",
      },
      {
        matchName: "match21",
        matchType: "final",
        category: "men",
        team1: "tbd",
        team2: "tbd",
        time: "5:30PM",
        location: "SAC TT Court-1",
      },
    ],
    badminton: [
      {
        matchName: "match14",
        matchType: "semi-final",
        category: "men",
        team1: "outr",
        team2: "utkal",
        time: "9:00 am",
        location: "sac court-1",
      },
      {
        matchName: "match15",
        matchType: "semi-final",
        category: "men",
        team1: "iitbbs-b",
        team2: "cv-raman",
        time: "9:00 am",
        location: "sac court-2",
      },
      {
        matchName: "match17",
        matchType: "semi-final",
        category: "women",
        team1: "outr",
        team2: "aiims",
        time: "9:00 am",
        location: "sac court-1",
      },
      {
        matchName: "match18",
        matchType: "semi-final",
        category: "women",
        team1: "xim",
        team2: "iitbbs-a",
        time: "9:00 am",
        location: "sac court-2",
      },
      {
        matchName: "match16",
        matchType: "final",
        category: "men",
        team1: "tbd",
        team2: "tbd",
        time: "6:00 pm",
        location: "sac Court-1",
      },
      {
        matchName: "match19",
        matchType: "final",
        category: "women",
        team1: "tbd",
        team2: "tbd",
        time: "3:00 pm",
        location: "sac Court-1",
      },
    ],
  },
};







